spring:
  # 服务名称
  application:
    name: charging-pile-system
  cloud:
    nacos:
      discovery:
        server-addr: 43.142.80.254:9848 # nacos地址
  datasource:
    username: root
    password: password
    url: jdbc:mysql://43.142.80.254:13306/charging_pile_system?characterEncoding=utf8&useUnicode=true&verifyServerCertificate=false&useSSL=false&requireSSL=false&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 43.142.80.254
    port: 6479
    password: password
    lettuce:
      pool:
        max-active:  8
        max-wait: 100
        max-idle: 8
        min-idle: 0

mqtt:
  enable: true
  host: tcp://101.132.244.232:2883
  username: root
  password: password
  timeout: 10
  keepAlive: 60
  topic: CDZ/#

mybatis:
  # mapper.xml文件扫描路径
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 开启驼峰映射，使得数据库字段与实体类映射起来
    map-underscore-to-camel-case: true

logging:
  level:
    com.example.chargingPileSystem.mapper: info
