
spring:

  # 服务名称
  application:
    name: charging-pile-system
  datasource:
    username: root
    password: password
    url: jdbc:mysql://118.31.104.26:13306/new_charging_pile_system?characterEncoding=utf8&useUnicode=true&verifyServerCertificate=false&useSSL=false&requireSSL=false&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 118.31.104.26
    port: 6479
    password: password
    lettuce:
      pool:
        max-active:  8
        max-wait: 100
        max-idle: 8
        min-idle: 0

mqtt:
  enable: true
  host: tcp://101.132.244.232:2883
  username: root
  password: password
  timeout: 10
  keepAlive: 60
  topic: CDZ/#

mybatis:
  # mapper.xml文件扫描路径
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 开启驼峰映射，使得数据库字段与实体类映射起来
    map-underscore-to-camel-case: true

logging:
  level:
    com.example.chargingPileSystem.mapper: info

# 微信核心参数
wechat:
  appId: wx04a5a6484e9716c2
  appSecret: Zjr12345678912345678912345678900
server:
  port: 8089
